routes/web.php
<?php

use App\Http\Controllers\Cabinet\SettingController;
use App\Http\Controllers\ExecutorsController;
use App\Http\Controllers\Task\ApplicationController;
use App\Http\Controllers\Task\ResourceController;
use App\Http\Controllers\Task\ReviewController;
use App\Http\Controllers\Task\UserTaskController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\RegistrationController;
use App\Http\Controllers\Admin\User\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\Organization\OrganizationController;
use App\Http\Controllers\Cabinet\Profile\UserProfileController;
use App\Http\Controllers\Cabinet\Profile\OrganizationProfileController;
use App\Http\Controllers\Admin\Handbook\HandbookTitleController;
use App\Http\Controllers\Admin\Handbook\HandbookController;
use App\Http\Controllers\Cabinet\Task\TaskController;
use \App\Http\Controllers\Admin\Task\TaskController as AdminTaskController;
use App\Http\Controllers\Cabinet\Message\ChatController;


Route::get('/', [HomeController::class, 'index'])->name('home');

Route::post('/message/{user}',[\App\Http\Controllers\MessageController::class,'message']);

Route::group(
    [
    'prefix' => 'registration',
    'as' => 'registration.'
    ],
    function (){
        Route::get('/',[RegistrationController::class,'registerTab'])->name('tab');
        Route::get('individual',[RegistrationController::class,'individual'])->name('individual');
        Route::get('entity',[RegistrationController::class,'entity'])->name('entity');
        Route::post('user',[RegistrationController::class,'user'])->name('user');
        Route::post('organization',[RegistrationController::class,'organization'])->name('organisation');
    }
);

Auth::routes();

Route::group(
    [
        'prefix' => 'cabinet',
        'as' => 'cabinet.',
        'namespace' => 'Cabinet',
        'middleware' => ['auth'],
    ],
    function () {
        Route::group([
            'prefix' => 'profile',
            'as' => 'profile.',
            'namespace' => 'Profile',
        ],function (){
            Route::group([
                'prefix'=>'user', 'as'=> 'user.', 'namespace'=>'User'],function (){
                Route::get('/{user}',[UserProfileController::class,'form'])->name('form');
                Route::post('/add_avatar',[UserProfileController::class,'addAvatar'])->name('avatar.create');
                Route::delete('/delete_avatar/{user}',[UserProfileController::class,'deleteAvatar'])->name('avatar.delete');
                Route::post('/add_file',[UserProfileController::class,'addFile'])->name('file.create');
                Route::post('/car',[UserProfileController::class,'addCarForm'])->name('car');
                Route::post('/category',[UserProfileController::class,'addCategoryForm'])->name('category');
                Route::post('/sub_category',[UserProfileController::class,'addSubCategory'])->name('sub.category');
                Route::put('/store/{user}',[UserProfileController::class,'store'])->name('store');
                Route::delete('/delete_car',[UserProfileController::class,'deleteCar'])->name('car.delete');
            });

            Route::group(['prefix'=>'organization','as'=>'organization.','namespace'=>'Organization'],function (){
                Route::get('/create/{user}',[OrganizationProfileController::class,'create'])->name('create');
                Route::post('/create/{user}',[OrganizationProfileController::class,'store'])->name('store');
                Route::get('/edit/{user}',[OrganizationProfileController::class,'edit'])->name('edit');
                Route::put('/edit/{user}',[OrganizationProfileController::class,'update'])->name('update');
                Route::post('/category',[OrganizationProfileController::class,'addCategoryForm'])->name('category');
                Route::post('/sub_category',[OrganizationProfileController::class,'addSubCategory'])->name('sub.category');
                Route::post('/add_logo',[OrganizationProfileController::class,'addLogo'])->name('logo.create');
                Route::delete('/delete_logo/{user}',[OrganizationProfileController::class,'deleteLogo'])->name('logo.delete');
            });
        });
        Route::group(['prefix'=>'setting','as'=>'setting.','namespace'=>'Setting'],function(){
            Route::get('/{user}',[SettingController::class,'form'])->name('form');
            Route::put('/edit/{user}',[SettingController::class,'store'])->name('edit');
        });
        Route::group(['prefix'=>'task','as'=>'task.','namespace'=>'Task'],function(){
            Route::get('/{user}/customer/{status?}',[TaskController::class,'customer'])->name('customer');
            Route::get('/{user}/executor/{status?}',[TaskController::class,'executor'])->name('executor');
            Route::get('/{user}/reviews/customer',[\App\Http\Controllers\Cabinet\Task\ReviewController::class,'customer'])->name('reviews.customer');
            Route::get('/{user}/reviews/executor',[\App\Http\Controllers\Cabinet\Task\ReviewController::class,'executor'])->name('reviews.executor');
        });
        Route::group(['prefix'=>'message','as'=>'message.','namespace'=>'Message'],function(){
            Route::get('/{user}/chats/{opponents?}',[ChatController::class,'index'])->name('chats');
            Route::post('/{user}/chatroom',[ChatController::class,'chatroom'])->name('chatroom');
        });
        Route::get('/{user}/resumes/',[\App\Http\Controllers\Cabinet\ResumeController::class,'index'])->name('resume');
        Route::get('/{user}/vacancies/',[\App\Http\Controllers\Cabinet\VacanciesController::class,'index'])->name('vacancy');
        Route::get('/{user}/notification',[\App\Http\Controllers\Cabinet\Message\NotificationController::class,'index'])->name('notification');
        Route::get('/notification/view/{notification}',[\App\Http\Controllers\Cabinet\Message\NotificationController::class,'view'])->name('notification.view');
    });



Route::namespace('Executors')->prefix('executors')->as('executors.')->group(function(){
    Route::get('/',[ExecutorsController::class,'index'])->name('executors');
    Route::get('/category/{slug}',[ExecutorsController::class,'getBySlug'])->name('category');
});

Route::get('/user/{user}',[App\Http\Controllers\UserController::class,'show'])->name('user');

Route::namespace('Task')->prefix('task')->as('task.')->group(function (){
    Route::get('/',[ResourceController::class,'index'])->name('index');
    Route::get('/category/{slug}',[ResourceController::class,'getBySlug'])->name('category');
    Route::get('/show/{slug}',[ResourceController::class,'show'])->name('show');
    Route::namespace('Resource')->prefix('resource')->as('resource.')->middleware(['auth'])->group(function(){
        Route::get('/create',[ResourceController::class,'form'])->name('form');
        Route::post('/start/{task?}',[ResourceController::class,'start'])->name('start');
        Route::post('/finish/{task?}',[ResourceController::class,'finish'])->name('finish');
        Route::post('/full/{task?}',[ResourceController::class,'full'])->name('full');
        Route::post('/date/{task}',[ResourceController::class,'date'])->name('date');
        Route::post('/create',[ResourceController::class,'store'])->name('store');
        Route::post('/sub_category',[ResourceController::class,'addSubCategory'])->name('sub.category');
        Route::get('/update/{task}',[ResourceController::class,'update'])->name('update');
        Route::put('/edit/{task}',[ResourceController::class,'edit'])->name('edit');
        Route::delete('delete/{task}',[ResourceController::class,'delete'])->name('delete');
    });
    Route::namespace('User')->prefix('user')->as('user.')->group(function (){
        Route::get('/create/{user}',[UserTaskController::class,'create'])->name('create');
        Route::post('/create/{user}',[UserTaskController::class,'store'])->name('store');
        Route::post('/start',[UserTaskController::class,'start'])->name('start');
    });
    Route::namespace('Application')->prefix('application')->as('application.')->middleware(['auth'])->group(function(){
        Route::post('/create/{task}',[ApplicationController::class,'create'])->name('create');
        Route::post('/add-general/{task}',[ApplicationController::class,'addGeneralApplication'])->name('add.general');
        Route::get('/refused/{application}',[ApplicationController::class,'refused'])->name('refused');
        Route::get('/closed/{application}',[ApplicationController::class,'closed'])->name('closed');
    });
    Route::post('/add_reviews/{application}',[ReviewController::class,'addReviews'])->name('add.reviews');
});

Route::group(
    [
        'prefix' => 'vacancy',
        'as' => 'vacancy.',
        'namespace' => 'Vacancy',
    ],
    function(){
        Route::get('/',[\App\Http\Controllers\Vacancy\VacancyController::class,'index'])->name('index');
        Route::get('/create',[\App\Http\Controllers\Vacancy\VacancyController::class,'create'])->middleware('auth')->name('create');
        Route::post('/create',[\App\Http\Controllers\Vacancy\VacancyController::class,'store'])->middleware('auth')->name('store');
        Route::get('/edit/{vacancy}',[\App\Http\Controllers\Vacancy\VacancyController::class,'edit'])->middleware('auth')->name('edit');
        Route::put('/edit/{vacancy}',[\App\Http\Controllers\Vacancy\VacancyController::class,'update'])->middleware('auth')->name('update');
        Route::get('/show/{vacancy}',[\App\Http\Controllers\Vacancy\VacancyController::class,'show'])->name('show');
        Route::get('/{category}',[\App\Http\Controllers\Vacancy\VacancyController::class,'getByCategoryId'])->name('category');
        Route::delete('/{vacancy}',[\App\Http\Controllers\Vacancy\VacancyController::class,'remove'])->name('remove');

resources/views/about_us.blade.php
@extends('layouts.app')
@section('meta')
    <title>О нас</title>
@endsection
@section('content')
<section class="content">
    <div class="container">
        <h1>О нас</h1>
        <p class="subhead">под заголовок</p>
        <div class="row">
            <div class="col-xs-12 col-md-9">
                <h3>Название</h3>
                <p>Пояснения</p>
            </div>
        </div>
    </div>
</section>
@endsection

resources/views/frequency.blade.php
@extends('layouts.app')
@section('meta')
    <title>Частые вопросы</title>
@endsection
@section('content')
    <section class="content">
    <div class="container">
        <h1>Частые вопросы</h1>
        <p class="subhead">Выберите подходящую тему</p>
        <div class="row">
            <div class="col-xs-12 col-md-6">
            @foreach($frequencyTitles as $title)

                <div class="questions-category">
                    <p class="h3">
                        <a href="#">{{$title->title}}</a>
                    </p>
                    <p>{{$title->description}}</p>
                    <div class="questions-expand">
                        <button class="btn" type="button" data-toggle="collapse" data-target="#collapseQuestion_{{$count}}" aria-expanded="false" aria-controls="collapseQuestion_1">
                            В разделе {{count($title->sections)}} вопросов
                            <svg width="10" height="5" viewBox="0 0 11 5" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M4.99831 4.99831C4.8315 4.99864 4.66985 4.94054 4.5414 4.83411L0.257904 1.26453C0.11211 1.14335 0.020426 0.969215 0.00302094 0.780437C-0.0143842 0.591658 0.0439156 0.403697 0.165095 0.257904C0.286274 0.11211 0.460406 0.020426 0.649185 0.00302095C0.837963 -0.0143841 1.02592 0.0439153 1.17172 0.165095L4.99831 3.36344L8.82491 0.279322C8.89793 0.22002 8.98196 0.175734 9.07215 0.149011C9.16235 0.122288 9.25693 0.113654 9.35048 0.123605C9.44402 0.133557 9.53468 0.161897 9.61723 0.206998C9.69979 0.252099 9.77261 0.313071 9.83153 0.386409C9.89691 0.459815 9.94642 0.545932 9.97697 0.639365C10.0075 0.732798 10.0185 0.831533 10.0091 0.929385C9.99968 1.02724 9.9702 1.1221 9.92245 1.20802C9.8747 1.29395 9.80972 1.36908 9.73158 1.42873L5.44808 4.87695C5.31594 4.96655 5.15759 5.00928 4.99831 4.99831Z" fill="url(#paint0_linear)"/>
                                <defs>
                                    <linearGradient id="paint0_linear" x1="10.0123" y1="1.41884e-06" x2="-0.340848" y2="2.76792" gradientUnits="userSpaceOnUse">
                                        <stop stop-color="#53EA98"/>
                                        <stop offset="0.515625" stop-color="#8EC5FC"/>
                                        <stop offset="1" stop-color="#AE8FC5"/>
                                    </linearGradient>
                                </defs>
                            </svg>
                        </button>
                        <div class="collapse" id="collapseQuestion_{{$count}}">
                            <div class="well">
                                @foreach($title->sections as $section)
                                    <div class="question">
                                    <a href="#">{{$section->title}}</a>
                                    <span>{{$section->description}}</span>
                                </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            @if($count == (int)$inTwo)
                </div>
                <div class="col-xs-12 col-md-6">
            @endif
            @php
                $count++;
            @endphp
            @endforeach
            </div>
        </div>
    </div>
</section>
@endsection
@section('scripts')
    <script type="text/javascript">
        $(document).ready(function() {
            $('.ui.dropdown').dropdown();
        });
    </script>
@endsection

resources/views/index.blade.php
@extends('layouts.app')
@section('meta')
    <title>Хочу могу</title>
@endsection
@section('content')
    <section class="main-screen">
        <div class="container">
            <p class="lead">Сервис позволяет найти специалистов во всех сферах услуг</p>
            <img height="515" src="svg/main-txt.svg" alt="картинка главного экрана">
            <div class="actions">
                <a href="{{route('task.resource.form')}}" class="action fs-27">
                    <p>Создать задание</p>
                </a>
                <a href="{{route('executors.executors')}}" class="action fs-20">
                    <p>Исполнители</p>
                </a>
                <a href="{{route('vacancy.index')}}" class="action fs-18">
                    <p>Вакансии</p>
                </a>
            </div>
        </div>
    </section>
    <section class="categories">
        <div class="container">
            <p class="h1 text-center">Исполнители готовы выполнить Ваше задание</p>
            <p class="text-center">Готовы помочь вам в решении самых разнообразных задач</p>
            <div class="row">
                <div class="col-xs-12 col-md-4">
                    @php
                        $count=0;
                    @endphp
                    @foreach($categoriesArray as $key=>$category)
                            <a href="{{route(is_object(Auth::user())?'task.category':'executors.category',$category['category']->slug)}}" class="category">
                                <i class="icon">
                                    <img src="{{$category['icon']}}" alt="{{$category['category']->name}}" width=40 height=40>
                                </i>
                                <div class="info">
                                    <p><strong>{{$category['category']->name}}</strong><small>{{$category['count']}} заданий</small></p>
                                </div>
                            </a>
                        @php
                            $count++;
                        @endphp
                        @if($count!=0&&($count%6)==0)

                            </div>
                            <div class="col-xs-12 col-md-4">
                        @endif
                    @endforeach
                </div>
        </div>
    </section>
    <section class="how-it-works">
        <div class="container">
            <p class="h1 text-center">Как это работает</p>
            <p class="text-center">Расскажите о задаче — исполнители напишут сами</p>
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <div class="how text-center">
                        <img src="svg/secure-data.svg" alt="как работает 1">
                        <p class="lead">Разместите заказ</p>
                        <p>Опишите задачу. Если нужно, укажите сроки и бюджет</p>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-4">
                    <div class="how text-center">
                        <img src="svg/select.svg" alt="как работает 1">
                        <p class="lead">Получите предложения</p>
                        <p>Исполнители сами откликнутся на ваш заказ. Обсудите детали заказа.</p>
                    </div>
                </div>
                <div class="col-xs-12 col-md-4">
                    <div class="how text-center">
                        <img src="svg/id-card.svg" alt="как работает 1">
                        <p class="lead">Выберите исполнителя</p>
                        <p>Выберите подходящего вам исполнителя по рейтингу, отзывам и цене</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/support.blade.php
@extends('layouts.app')
@section('meta')
    <title>Служба поддержки</title>
@endsection
@section('content')
    <section class="content">
        <div class="container">
            <h1>Служба поддержки</h1>
            <p class="subhead">под заголовок</p>
            <div class="row">
                <div class="col-xs-12 col-md-9">
                    <h3>Название</h3>
                    <p>Пояснения</p>
                </div>
            </div>
        </div>
    </section>
@endsection