routes/web.php
                Route::post('/add_avatar',[UserProfileController::class,'addAvatar'])->name('avatar.create');
                Route::delete('/delete_avatar/{user}',[UserProfileController::class,'deleteAvatar'])->name('avatar.delete');
                Route::post('/add_file',[UserProfileController::class,'addFile'])->name('file.create');
                Route::post('/car',[UserProfileController::class,'addCarForm'])->name('car');
                Route::post('/category',[UserProfileController::class,'addCategoryForm'])->name('category');
                Route::post('/sub_category',[UserProfileController::class,'addSubCategory'])->name('sub.category');
                Route::put('/store/{user}',[UserProfileController::class,'store'])->name('store');
                Route::delete('/delete_car',[UserProfileController::class,'deleteCar'])->name('car.delete');
            });

            Route::group(['prefix'=>'organization','as'=>'organization.','namespace'=>'Organization'],function (){
                Route::get('/create/{user}',[OrganizationProfileController::class,'create'])->name('create');
                Route::post('/create/{user}',[OrganizationProfileController::class,'store'])->name('store');
                Route::get('/edit/{user}',[OrganizationProfileController::class,'edit'])->name('edit');
                Route::put('/edit/{user}',[OrganizationProfileController::class,'update'])->name('update');
                Route::post('/category',[OrganizationProfileController::class,'addCategoryForm'])->name('category');
                Route::post('/sub_category',[OrganizationProfileController::class,'addSubCategory'])->name('sub.category');
                Route::post('/add_logo',[OrganizationProfileController::class,'addLogo'])->name('logo.create');
                Route::delete('/delete_logo/{user}',[OrganizationProfileController::class,'deleteLogo'])->name('logo.delete');
            });
        });
        Route::group(['prefix'=>'setting','as'=>'setting.','namespace'=>'Setting'],function(){
            Route::get('/{user}',[SettingController::class,'form'])->name('form');
            Route::put('/edit/{user}',[SettingController::class,'store'])->name('edit');
        });
        Route::group(['prefix'=>'task','as'=>'task.','namespace'=>'Task'],function(){
            Route::get('/{user}/customer/{status?}',[TaskController::class,'customer'])->name('customer');
            Route::get('/{user}/executor/{status?}',[TaskController::class,'executor'])->name('executor');
            Route::get('/{user}/reviews/customer',[\App\Http\Controllers\Cabinet\Task\ReviewController::class,'customer'])->name('reviews.customer');
            Route::get('/{user}/reviews/executor',[\App\Http\Controllers\Cabinet\Task\ReviewController::class,'executor'])->name('reviews.executor');
        });
        Route::group(['prefix'=>'message','as'=>'message.','namespace'=>'Message'],function(){
            Route::get('/{user}/chats/{opponents?}',[ChatController::class,'index'])->name('chats');
            Route::post('/{user}/chatroom',[ChatController::class,'chatroom'])->name('chatroom');
        });
        Route::get('/{user}/resumes/',[\App\Http\Controllers\Cabinet\ResumeController::class,'index'])->name('resume');
        Route::get('/{user}/vacancies/',[\App\Http\Controllers\Cabinet\VacanciesController::class,'index'])->name('vacancy');
        Route::get('/{user}/notification',[\App\Http\Controllers\Cabinet\Message\NotificationController::class,'index'])->name('notification');
        Route::get('/notification/view/{notification}',[\App\Http\Controllers\Cabinet\Message\NotificationController::class,'view'])->name('notification.view');
    });



Route::namespace('Executors')->prefix('executors')->as('executors.')->group(function(){
    Route::get('/',[ExecutorsController::class,'index'])->name('executors');
    Route::get('/category/{slug}',[ExecutorsController::class,'getBySlug'])->name('category');
});

Route::get('/user/{user}',[App\Http\Controllers\UserController::class,'show'])->name('user');

Route::namespace('Task')->prefix('task')->as('task.')->group(function (){
    Route::get('/',[ResourceController::class,'index'])->name('index');
    Route::get('/category/{slug}',[ResourceController::class,'getBySlug'])->name('category');
    Route::get('/show/{slug}',[ResourceController::class,'show'])->name('show');
    Route::namespace('Resource')->prefix('resource')->as('resource.')->middleware(['auth'])->group(function(){
        Route::get('/create',[ResourceController::class,'form'])->name('form');
        Route::post('/start/{task?}',[ResourceController::class,'start'])->name('start');
        Route::post('/finish/{task?}',[ResourceController::class,'finish'])->name('finish');
        Route::post('/full/{task?}',[ResourceController::class,'full'])->name('full');
        Route::post('/date/{task}',[ResourceController::class,'date'])->name('date');
        Route::post('/create',[ResourceController::class,'store'])->name('store');
        Route::post('/sub_category',[ResourceController::class,'addSubCategory'])->name('sub.category');
        Route::get('/update/{task}',[ResourceController::class,'update'])->name('update');
        Route::put('/edit/{task}',[ResourceController::class,'edit'])->name('edit');
        Route::delete('delete/{task}',[ResourceController::class,'delete'])->name('delete');
    });
    Route::namespace('User')->prefix('user')->as('user.')->group(function (){
        Route::get('/create/{user}',[UserTaskController::class,'create'])->name('create');
        Route::post('/create/{user}',[UserTaskController::class,'store'])->name('store');
        Route::post('/start',[UserTaskController::class,'start'])->name('start');
    });
    Route::namespace('Application')->prefix('application')->as('application.')->middleware(['auth'])->group(function(){
        Route::post('/create/{task}',[ApplicationController::class,'create'])->name('create');
        Route::post('/add-general/{task}',[ApplicationController::class,'addGeneralApplication'])->name('add.general');
        Route::get('/refused/{application}',[ApplicationController::class,'refused'])->name('refused');
        Route::get('/closed/{application}',[ApplicationController::class,'closed'])->name('closed');
    });
    Route::post('/add_reviews/{application}',[ReviewController::class,'addReviews'])->name('add.reviews');
});

Route::group(
    [
        'prefix' => 'vacancy',
        'as' => 'vacancy.',
        'namespace' => 'Vacancy',
    ],
    function(){
        Route::get('/',[\App\Http\Controllers\Vacancy\VacancyController::class,'index'])->name('index');
        Route::get('/create',[\App\Http\Controllers\Vacancy\VacancyController::class,'create'])->middleware('auth')->name('create');
        Route::post('/create',[\App\Http\Controllers\Vacancy\VacancyController::class,'store'])->middleware('auth')->name('store');
        Route::get('/edit/{vacancy}',[\App\Http\Controllers\Vacancy\VacancyController::class,'edit'])->middleware('auth')->name('edit');
        Route::put('/edit/{vacancy}',[\App\Http\Controllers\Vacancy\VacancyController::class,'update'])->middleware('auth')->name('update');
        Route::get('/show/{vacancy}',[\App\Http\Controllers\Vacancy\VacancyController::class,'show'])->name('show');
        Route::get('/{category}',[\App\Http\Controllers\Vacancy\VacancyController::class,'getByCategoryId'])->name('category');
        Route::delete('/{vacancy}',[\App\Http\Controllers\Vacancy\VacancyController::class,'remove'])->name('remove');
        Route::get('respond/{vacancy}',[\App\Http\Controllers\Vacancy\VacancyController::class,'respond'])->name('respond');
    });

Route::group(
    [
        'prefix' => 'resume',
        'as' => 'resume.',
        'namespace' => 'Resume',
    ],
    function(){
        Route::get('/',[\App\Http\Controllers\Resume\ResumeController::class,'index'])->name('index');

        Route::get('/create',[\App\Http\Controllers\Resume\ResumeController::class,'create'])->middleware('auth')->name('create');
        Route::post('/create',[\App\Http\Controllers\Resume\ResumeController::class,'store'])->middleware('auth')->name('store');
        Route::get('/edit/{resume}',[\App\Http\Controllers\Resume\ResumeController::class,'edit'])->middleware('auth')->name('edit');
        Route::put('/edit/{resume}',[\App\Http\Controllers\Resume\ResumeController::class,'update'])->middleware('auth')->name('update');
        Route::post('/experience',[\App\Http\Controllers\Resume\ResumeController::class,'experience'])->middleware('auth')->name('experience');
        Route::post('/education',[\App\Http\Controllers\Resume\ResumeController::class,'education'])->middleware('auth')->name('education');
        Route::get('/show/{resume}',[\App\Http\Controllers\Resume\ResumeController::class,'show'])->name('show');
        Route::delete('/{resume}',[\App\Http\Controllers\Resume\ResumeController::class,'remove'])->name('remove');
        Route::get('/{category}',[\App\Http\Controllers\Resume\ResumeController::class,'getByCategoryId'])->name('category');
        Route::get('/respond/{resume}',[\App\Http\Controllers\Resume\ResumeController::class,'respond'])->name('respond');
    });

Route::namespace('Admin')->prefix('admin')->as('admin.')->middleware(['auth', 'can:admin-panel'])->group(
    function(){
        Route::get('/',[AdminController::class,'index'])->name('index');
        Route::namespace('User')->prefix('user')->as('user.')->group(function (){
            Route::get('/',[UserController::class,'index'])->name('index')->name('index');
            Route::get('/edit/{user}',[UserController::class,'editForm'])->name('form');
            Route::put('/edit/{user}',[UserController::class,'edit'])->name('edit');
            Route::get('/view/{user}',[UserController::class,'view'])->name('view');
        });
        Route::namespace('Region')->prefix('region')->as('region.')->group(function (){

app/Http/Controllers/Admin/Vacancy/VacancyController.php
<?php

namespace App\Http\Controllers\Admin\Vacancy;

use App\Entities\Vacancy\Vacancy;
use App\Helpers\ArrayHelpers;
use App\Http\Controllers\Controller;
use App\Services\CategoryService;
use App\Services\Vacancy\VacancyService;
use Illuminate\Http\Request;

class VacancyController extends Controller
{
    public $service;
    public $categoryService;

    public function __construct(VacancyService $service,CategoryService $categoryService)
    {
        $this->service=$service;
        $this->categoryService=$categoryService;
    }

    public function index()
    {
        $vacancies=$this->service->repository->all();
        $categoryParent=array_merge([''=>''],ArrayHelpers::map($this->categoryService->repository->allParent(),'name','name'));
        return view('admin.vacancy.index',compact('vacancies','categoryParent'));
    }

    public function show(Vacancy $vacancy)
    {
        return view('admin.vacancy.show',compact('vacancy'));
    }

    public function destroy(Vacancy $vacancy)
    {
        $this->service->delete($vacancy);
        return redirect()->route('admin.vacancy.show',$vacancy)
        ->with('success', 'Вакансия удалена');
    }

}

app/Http/Controllers/Cabinet/VacanciesController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Entities\User\User;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class VacanciesController extends Controller
{
    public function index(User $user)
    {
        $vacancies=$user->vacancies;
        return view('cabinet.vacancy',compact('vacancies','user'));
    }
}

app/Http/Controllers/Vacancy/VacancyController.php
<?php

namespace App\Http\Controllers\Vacancy;

use App\Entities\Category;
use App\Entities\Resume\Resume;
use App\Entities\Vacancy\Vacancy;
use App\Events\NotificationEvent;
use App\Http\Controllers\Controller;
use App\Http\Requests\Vacancy\EditRequest;
use App\Http\Requests\Vacancy\SearchRequest;
use App\Http\Search\VacancySearch;
use App\Services\CategoryService;
use App\Services\Handbook\HandbookService;
use App\Services\Vacancy\VacancyService;
use Illuminate\Http\Request;
use App\Http\Requests\Vacancy\CreateRequest;

class VacancyController extends Controller
{

    public $categoryService;
    public $handbookService;
    public $service;

    public function __construct(CategoryService $categoryService,HandbookService $handbookService,VacancyService $service)
    {
        $this->categoryService=$categoryService;
        $this->handbookService=$handbookService;
        $this->service=$service;
    }


    public function index(SearchRequest $request)
    {
        $categories=$this->categoryService->dropDownParent();
        $vacancies=(new VacancySearch())->search($request);
        $requestArr=$request->all();
        return view('vacancy.index',compact('vacancies','categories','requestArr'));
    }

    public function create()
    {
        return view('vacancy.create',[
            'categories'=>$this->categoryService->dropDownParent(),
            'works'=>$this->handbookService->dropDownHandbook('work'),
            'salarys'=>$this->handbookService->dropDownHandbook('salary')
        ]);
    }

    public function store(CreateRequest $request)
    {
        try{
            $vacancy=$this->service->create($request);
            return redirect()->route('vacancy.show',$vacancy)
                ->with('success', 'Резюме сохранено');
        }catch (\RuntimeException $e){
            return redirect()->route('vacancy.create')
                ->with('error', 'Вакансия  не сохранена');
        }

    }

    public function edit(Vacancy $vacancy)
    {
        return view('vacancy.edit',[
            'categories'=>$this->categoryService->dropDownParent(),
            'works'=>$this->handbookService->dropDownHandbook('work'),
            'salarys'=>$this->handbookService->dropDownHandbook('salary'),
            'vacancy'=>$vacancy
        ]);
    }

    public function update(EditRequest $request,Vacancy $vacancy)
    {
        try{
            $this->service->edit($request,$vacancy);
            return redirect()->route('vacancy.show',$vacancy);
        }catch (\RuntimeException $e)
        {
            return redirect()->route('vacancy.edit',$vacancy)
                ->with('error','Вакансия не сохранена');
        }
    }

    public function show(Vacancy $vacancy)
    {
        return view('vacancy.show',compact('vacancy'));
    }

    public function remove(Vacancy $vacancy)
    {
        $this->service->delete($vacancy);
    }

    public function getByCategoryId(Category $category)
    {
        $vacancies=$category->vacancy()->paginate(12);
        $categories=$this->categoryService->dropDownParent();
        $requestArr=[];
        return view('vacancy.index',compact('vacancies','categories','requestArr'));
    }

    public function respond(Vacancy $vacancy)
    {
        event(new NotificationEvent(Vacancy::class,$vacancy->id,$vacancy->user));
        return redirect()->route('vacancy.show',$vacancy)
            ->with('success','Вы откликнулись');
    }



}

resources/views/admin/vacancy/index.blade.php
@extends('adminlte::page')
@section('plugins.DateRange', true)
@section('plugins.Datatables', true)
@section('plugins.Select2', true)
@section('title', 'Вакансии')
@section('content_header')
    <h1>Вакансии</h1>
@stop

@section('content')
    <div class="card shadow mb-4">
        <div class="card-body">
            <table id="example" class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>Название</th>
                    <th>Пользователь</th>
                    <th>Дата создания</th>
                    <th>Категория</th>
                    <th></th>
                </tr>
                <tr>
                    <th>{{Form::text('name',old('name'),['id'=>'name','class'=>'form-control'])}}</th>
                    <th>{{Form::text('author_user_id',old('author_user_id'),['id'=>'user','class'=>'form-control'])}}</th>
                    <th>{{Form::text('created_at',old('created_at'),['id'=>'created','class'=>'form-control'])}}</th>
                    <th>{{Form::select('category_id',$categoryParent,old('category'),['id'=>'category','class'=>'form-control'])}}</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($vacancies as $vacancy)
                    <tr>
                        <td>{{$vacancy->name}}</td>
                        <td><a href="{{route('admin.user.view',$vacancy->user)}}">{{$vacancy->user->name}}</a></td>
                        <td>{{$vacancy->created_at}}</td>
                        <td>{{$vacancy->category->name}}</td>
                        <td>
                            <a href="{{route('admin.vacancy.view',$vacancy)}}">
                                <i class="far fa-eye"></i>
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('js')
    <script>

        $(document).ready(function() {
            let table = $('#example').DataTable();
            $('#name').keyup( function() {
                $.fn.dataTable.ext.search.push(
                    function( settings, data, dataIndex ) {
                        let name =  $('#name').val();
                        if (data[0].toLowerCase().indexOf(name.toLowerCase())>=0){
                            return true;
                        }
                        return false;
                    }
                );
                table.draw();
            } );
            $('#user').keyup( function() {
                $.fn.dataTable.ext.search.push(
                    function( settings, data, dataIndex ) {
                        let user =  $('#user').val();
                        if (data[1].toLowerCase().indexOf(user)>=0){
                            return true;
                        }
                        return false;
                    }
                );
                table.draw();
            } );
            $('#created').daterangepicker({
                locale: {
                    format: 'YYYY-MM-DD',
                    separator:  ' : ',
                    applyLabel: "Применить",
                    cancelLabel: "Отменить",
                    monthNames: [
                        "Январь",
                        "февраль",
                        "Март",
                        "Апрель",
                        "Май",
                        "Июнь",
                        "Июль",
                        "Август",
                        "Сентябрь",
                        "Октябрь",
                        "Ноябрь",
                        "Декабрь"
                    ],
                }
            });
            $('#created_at').on("apply.daterangepicker",function(ev,picker){
                let date = $(this).val().split(' : ')
                $.fn.dataTable.ext.search.push(
                    function( settings, data, dataIndex ) {
                        if (moment(data[2]).isSameOrAfter(date[0]) && moment(data[2]).isSameOrBefore(date[1]) ){
                            return true;
                        }
                        return false;
                    }
                );
                table.draw();
            });
            $('#category').select2({ placeholder: "Выберите из списка",allowClear: true,language: "ru",});

            $('#category').on('select2:select', function() {
                $.fn.dataTable.ext.search.push(
                    function( settings, data, dataIndex ) {
                        let category =  $('#category').val();
                        if (data[4].indexOf(category)>=0){
                            return true;
                        }
                        return false;
                    }
                );
                table.draw();
            } );

        } );
    </script>
@stop

resources/views/admin/vacancy/show.blade.php
@extends('adminlte::page')

@section('title', $vacancy->name)

@section('content_header')
    <p class="h1">{{$vacancy->name}} </p>
@stop

@section('content')
    <div class="card">
        <div class="card-header">
            <div class="row">
                <div class="col-8">{{$vacancy->name}}</div>
                <div class="col-2">
                    {{Form::open(['route'=>['admin.vacancy.delete', $vacancy],'class'=>"mr-1",'method'=>'post'])}}
                    @method('DELETE')
                    <button class="btn btn-danger">Удалить</button>
                    {{Form::close()}}
                </div>
            </div>

        </div>
        <div class="card-body">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Ключ</th>
                    <th scope="col">Значение</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>id</td>
                    <td>{{$vacancy->id}}</td>
                </tr>
                <tr>
                    <td>Название ваукансии</td>
                    <td>{{$vacancy->name}}</td>
                </tr>
                @if(is_object($vacancy->category))
                    <tr>
                        <td>Категория</td>
                        <td>{{$vacancy->category->name}}</td>
                    </tr>
                @endif
                @if(is_object($vacancy->work))
                    <tr>
                        <td>График работы</td>
                        <td>{{$vacancy->work->title}}</td>
                    </tr>
                @endif
                <tr>
                    <td>Зарплата</td>
                    <td>{{$vacancy->salary}}</td>
                </tr>
                @if(is_object($vacancy->payments))
                    <tr>
                        <td>Дата и время начала работы</td>
                        <td>{{$vacancy->payments->title}}</td>
                    </tr>
                @endif
                <tr>
                    <td>Где предстоит работать</td>
                    <td>{{$vacancy->where_work}}</td>
                </tr>
                <tr>
                    <td>Адрес работы</td>
                    <td>{{$vacancy->adress_work}}</td>
                </tr>
                <tr>
                    <td>Требования к кандидату</td>
                    <td>{{$vacancy->requirements}}</td>
                </tr>
                @if(is_object($vacancy->payments))
                    <tr>
                        <td>Способ оплаты</td>
                        <td>{{$vacancy->payments->title}}</td>
                    </tr>
                @endif
                <tr>
                    <td>Обязанности</td>
                    <td>{{$vacancy->obligation}}</td>
                </tr>
                <tr>
                    <td>Описание вакансии и компании</td>
                    <td>{{$vacancy->description}}</td>
                </tr>
                <tr>
                    <td>Создатель вакансии</td>
                    <td><a href="{{route('admin.user.view',$vacancy->user)}}">{{$vacancy->user->name}}</a></td>
                </tr>
                <tr>
                    <td>Статус вакансии</td>
                    <td>{{$vacancy->is_close?'Закрыта':'Открыта'}}</td>
                </tr>
                <tr>
                    <td>Дата создания</td>
                    <td>{{$vacancy->created_at}}</td>
                </tr>
                <tr>
                    <td>Дата последнего редактирования</td>
                    <td>{{$vacancy->updated_at}}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

@stop