routes/web.php
<?php

use App\Http\Controllers\Cabinet\SettingController;
use App\Http\Controllers\ExecutorsController;
use App\Http\Controllers\Task\ApplicationController;
use App\Http\Controllers\Task\ResourceController;
use App\Http\Controllers\Task\ReviewController;
use App\Http\Controllers\Task\UserTaskController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\RegistrationController;
use App\Http\Controllers\Admin\User\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\Organization\OrganizationController;
use App\Http\Controllers\Cabinet\Profile\UserProfileController;
use App\Http\Controllers\Cabinet\Profile\OrganizationProfileController;
use App\Http\Controllers\Admin\Handbook\HandbookTitleController;
use App\Http\Controllers\Admin\Handbook\HandbookController;
use App\Http\Controllers\Cabinet\Task\TaskController;
use \App\Http\Controllers\Admin\Task\TaskController as AdminTaskController;
use App\Http\Controllers\Cabinet\Message\ChatController;


Route::get('/', [HomeController::class, 'index'])->name('home');

Route::post('/message/{user}',[\App\Http\Controllers\MessageController::class,'message']);

Route::group(
    [
    'prefix' => 'registration',
    'as' => 'registration.'
    ],
    function (){
        Route::get('/',[RegistrationController::class,'registerTab'])->name('tab');
        Route::get('individual',[RegistrationController::class,'individual'])->name('individual');
        Route::get('entity',[RegistrationController::class,'entity'])->name('entity');
        Route::post('user',[RegistrationController::class,'user'])->name('user');
        Route::post('organization',[RegistrationController::class,'organization'])->name('organisation');
    }
);

Auth::routes();

Route::group(
    [
        'prefix' => 'cabinet',
        'as' => 'cabinet.',
        'namespace' => 'Cabinet',
        'middleware' => ['auth'],
    ],
    function () {
        Route::group([
            'prefix' => 'profile',
            'as' => 'profile.',
            'namespace' => 'Profile',
        ],function (){
            Route::group([
                'prefix'=>'user', 'as'=> 'user.', 'namespace'=>'User'],function (){
                Route::get('/{user}',[UserProfileController::class,'form'])->name('form');
                Route::post('/add_avatar',[UserProfileController::class,'addAvatar'])->name('avatar.create');
                Route::delete('/delete_avatar/{user}',[UserProfileController::class,'deleteAvatar'])->name('avatar.delete');
                Route::post('/add_file',[UserProfileController::class,'addFile'])->name('file.create');
                Route::post('/car',[UserProfileController::class,'addCarForm'])->name('car');
                Route::post('/category',[UserProfileController::class,'addCategoryForm'])->name('category');
                Route::post('/sub_category',[UserProfileController::class,'addSubCategory'])->name('sub.category');
                Route::put('/store/{user}',[UserProfileController::class,'store'])->name('store');
                Route::delete('/delete_car',[UserProfileController::class,'deleteCar'])->name('car.delete');
            });

            Route::group(['prefix'=>'organization','as'=>'organization.','namespace'=>'Organization'],function (){
                Route::get('/create/{user}',[OrganizationProfileController::class,'create'])->name('create');
                Route::post('/create/{user}',[OrganizationProfileController::class,'store'])->name('store');
                Route::get('/edit/{user}',[OrganizationProfileController::class,'edit'])->name('edit');
                Route::put('/edit/{user}',[OrganizationProfileController::class,'update'])->name('update');
                Route::post('/category',[OrganizationProfileController::class,'addCategoryForm'])->name('category');
                Route::post('/sub_category',[OrganizationProfileController::class,'addSubCategory'])->name('sub.category');
                Route::post('/add_logo',[OrganizationProfileController::class,'addLogo'])->name('logo.create');
                Route::delete('/delete_logo/{user}',[OrganizationProfileController::class,'deleteLogo'])->name('logo.delete');
            });
        });
        Route::group(['prefix'=>'setting','as'=>'setting.','namespace'=>'Setting'],function(){
            Route::get('/{user}',[SettingController::class,'form'])->name('form');
            Route::put('/edit/{user}',[SettingController::class,'store'])->name('edit');
        });
        Route::group(['prefix'=>'task','as'=>'task.','namespace'=>'Task'],function(){
            Route::get('/{user}/customer/{status?}',[TaskController::class,'customer'])->name('customer');
            Route::get('/{user}/executor/{status?}',[TaskController::class,'executor'])->name('executor');
            Route::get('/{user}/reviews/customer',[\App\Http\Controllers\Cabinet\Task\ReviewController::class,'customer'])->name('reviews.customer');
            Route::get('/{user}/reviews/executor',[\App\Http\Controllers\Cabinet\Task\ReviewController::class,'executor'])->name('reviews.executor');
        });
        Route::group(['prefix'=>'message','as'=>'message.','namespace'=>'Message'],function(){
            Route::get('/{user}/chats/{opponents?}',[ChatController::class,'index'])->name('chats');
            Route::post('/{user}/chatroom',[ChatController::class,'chatroom'])->name('chatroom');
        });
        Route::get('/{user}/resumes/',[\App\Http\Controllers\Cabinet\ResumeController::class,'index'])->name('resume');
        Route::get('/{user}/vacancies/',[\App\Http\Controllers\Cabinet\VacanciesController::class,'index'])->name('vacancy');
        Route::get('/{user}/notification',[\App\Http\Controllers\Cabinet\Message\NotificationController::class,'index'])->name('notification');
        Route::get('/notification/view/{notification}',[\App\Http\Controllers\Cabinet\Message\NotificationController::class,'view'])->name('notification.view');
    });



Route::namespace('Executors')->prefix('executors')->as('executors.')->group(function(){
    Route::get('/',[ExecutorsController::class,'index'])->name('executors');
    Route::get('/category/{slug}',[ExecutorsController::class,'getBySlug'])->name('category');
});

Route::get('/user/{user}',[App\Http\Controllers\UserController::class,'show'])->name('user');

Route::namespace('Task')->prefix('task')->as('task.')->group(function (){
    Route::get('/',[ResourceController::class,'index'])->name('index');
    Route::get('/category/{slug}',[ResourceController::class,'getBySlug'])->name('category');
    Route::get('/show/{slug}',[ResourceController::class,'show'])->name('show');
    Route::namespace('Resource')->prefix('resource')->as('resource.')->middleware(['auth'])->group(function(){
        Route::get('/create',[ResourceController::class,'form'])->name('form');
        Route::post('/start/{task?}',[ResourceController::class,'start'])->name('start');
        Route::post('/finish/{task?}',[ResourceController::class,'finish'])->name('finish');
        Route::post('/full/{task?}',[ResourceController::class,'full'])->name('full');
        Route::post('/date/{task}',[ResourceController::class,'date'])->name('date');
        Route::post('/create',[ResourceController::class,'store'])->name('store');
        Route::post('/sub_category',[ResourceController::class,'addSubCategory'])->name('sub.category');
        Route::get('/update/{task}',[ResourceController::class,'update'])->name('update');
        Route::put('/edit/{task}',[ResourceController::class,'edit'])->name('edit');
        Route::delete('delete/{task}',[ResourceController::class,'delete'])->name('delete');
    });
    Route::namespace('User')->prefix('user')->as('user.')->group(function (){
        Route::get('/create/{user}',[UserTaskController::class,'create'])->name('create');
        Route::post('/create/{user}',[UserTaskController::class,'store'])->name('store');
        Route::post('/start',[UserTaskController::class,'start'])->name('start');
    });
    Route::namespace('Application')->prefix('application')->as('application.')->middleware(['auth'])->group(function(){
        Route::post('/create/{task}',[ApplicationController::class,'create'])->name('create');
        Route::post('/add-general/{task}',[ApplicationController::class,'addGeneralApplication'])->name('add.general');
        Route::get('/refused/{application}',[ApplicationController::class,'refused'])->name('refused');
        Route::get('/closed/{application}',[ApplicationController::class,'closed'])->name('closed');
    });
    Route::post('/add_reviews/{application}',[ReviewController::class,'addReviews'])->name('add.reviews');
});

Route::group(
    [
        'prefix' => 'vacancy',
        'as' => 'vacancy.',
        'namespace' => 'Vacancy',
    ],
    function(){
        Route::get('/',[\App\Http\Controllers\Vacancy\VacancyController::class,'index'])->name('index');
        Route::get('/create',[\App\Http\Controllers\Vacancy\VacancyController::class,'create'])->middleware('auth')->name('create');
        Route::post('/create',[\App\Http\Controllers\Vacancy\VacancyController::class,'store'])->middleware('auth')->name('store');
        Route::get('/edit/{vacancy}',[\App\Http\Controllers\Vacancy\VacancyController::class,'edit'])->middleware('auth')->name('edit');
        Route::put('/edit/{vacancy}',[\App\Http\Controllers\Vacancy\VacancyController::class,'update'])->middleware('auth')->name('update');
        Route::get('/show/{vacancy}',[\App\Http\Controllers\Vacancy\VacancyController::class,'show'])->name('show');
        Route::get('/{category}',[\App\Http\Controllers\Vacancy\VacancyController::class,'getByCategoryId'])->name('category');
        Route::delete('/{vacancy}',[\App\Http\Controllers\Vacancy\VacancyController::class,'remove'])->name('remove');

app/Http/Controllers/Cabinet/Message/ChatController.php
<?php

namespace App\Http\Controllers\Cabinet\Message;

use App\Entities\Chatroom;
use App\Entities\User\User;
use App\Http\Controllers\Controller;
use App\Services\ChatroomService;
use App\Services\User\UserService;
use http\Exception\RuntimeException;
use Illuminate\Http\Request;

class ChatController extends Controller
{
    public $service;
    public $userService;

    public function __construct(ChatroomService $service,UserService $userService)
    {
        $this->service=$service;
        $this->userService=$userService;
    }

    public function index(User $user,int $opponent_id=null)
    {
        $opponent=$opponent_id;
        if($opponent_id){
            $opponent=$this->userService->repository->one($opponent_id);
        }
        $first=$this->service->first($user,$opponent);
        return view('cabinet.chats.index',['user'=>$user,'chatrooms'=>$this->service->getRooms($user),'first'=>$first]);
    }

    public function chatroom(Request $request, User $user)
    {
        $request->validate([
            'room_id'=>'required|integer'
        ]);
        try {
            return $this->service->getChats($user,$request->room_id);
        }catch (\DomainException | \RuntimeException $e){
            return redirect()->route('cabinet.message.chatroom',$user)
                ->with('error', 'Заявка не подана');
        }

    }
}

app/Http/Controllers/Cabinet/Message/NotificationController.php
<?php

namespace App\Http\Controllers\Cabinet\Message;

use App\Entities\Notification;
use App\Entities\User\User;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class NotificationController extends Controller
{
    public function index(User $user)
    {
        $notifications=Notification::where('user_id',$user->id)->where('view',false)->get();
        return view('cabinet.notification',compact('user','notifications'));
    }

    public function view(Notification $notification)
    {
        $notification->view=true;
        $notification->save();
    }
}

app/Http/Controllers/Cabinet/Profile/OrganizationProfileController.php
<?php

namespace App\Http\Controllers\Cabinet\Profile;

use App\Entities\Organization\Organization;
use App\Entities\User\User;
use App\Http\Controllers\Controller;
use App\Http\Requests\Organization\AjaxSubCategoryRequest;
use App\Http\Requests\Organization\CabinetEditRequest;
use App\Http\Requests\Organization\CreateRequest;
use App\Http\Requests\Organization\RegisterRequest;
use App\Http\Requests\Organization\LogoRequest;
use App\Http\Requests\Organization\AjaxCategoryRequest;
use App\Services\CategoryService;
use App\Services\Organization\OrganizationService;
use App\Services\RegionService;
use Illuminate\Http\Request;

class OrganizationProfileController extends Controller
{
    public $service;
    public $categoryService;
    public $regionService;

    public function __construct(
        OrganizationService $service,
        CategoryService $categoryService,
        RegionService $regionService
    )
    {
        $this->service=$service;
        $this->categoryService=$categoryService;
        $this->regionService=$regionService;
    }


    public function addCategoryForm(AjaxCategoryRequest  $request)
    {
        $organisation=$this->service->organisationRepository->oneByUserId($request->user);
        if(!is_object($organisation)){
            return $this->returnViewCategory($request->name);
        }
        if(!$organisation->categories->isEmpty()&&!$request->is_new){
            $organizationParentCategory=$this->service->dropDownParentCategory($organisation);
            return view('cabinet.profile.user._category',[
                'name'=>$request->name,
                'parents'=>$this->categoryService->dropDownParent(),
                'userParentCategories'=>$organizationParentCategory,
                'userSubCategory'=>$organisation->sub_category_id
            ]);
        }
        return $this->returnViewCategory($request->name);
    }

    public function addSubCategory(AjaxSubCategoryRequest $request)
    {
        if(!empty($request->organization_id)){
            $organization=$this->service->organisationRepository->one($request->organization_id);
        }
        return view('cabinet.profile.user._subCategory',[
            'subCategories'=>$this->categoryService->getSubCategory($request->category_id),
            'userSubCategory'=>!empty($organization)?$organization->sub_category_id:null,
            'name'=>$request->name
        ]);
    }

    public function addLogo(LogoRequest $request)
    {
        $organization=$this->service->organisationRepository->one($request->organization);
        try {
            $this->service->addLogo($request,$organization);
            return redirect()->route('cabinet.profile.organization.edit', $organization->user)
                ->with('success', 'Логотип добавлен');
        }catch (\Exception $e){
            return redirect()->route('cabinet.profile.organization.edit',$organization->user)
                ->with('error', 'Логотип не добавлен');
        }
    }

    public function deleteLogo(Organization $organization)
    {
        try {
            $this->service->deleteLogo($organization);
            return redirect()->route('cabinet.profile.organization.form',$organization->user)
                ->with('success', 'Логотип удален');
        }catch (\Exception $e){
            return redirect()->route('cabinet.profile.organization.form',$organization->user)
                ->with('error', 'Логотип не удален');
        }

    }

    public function create(User $user){
        return view('cabinet.profile.organization.create',[
            'user'=>$user,
            'regions'=>$this->regionService->dropDownRegion()
        ]);
    }

    public function store(CreateRequest $request, User $user){
        try{
           $this->service->create($request,$user);
           return redirect()->route('cabinet.profile.organization.edit',$user)
                ->with('success', 'Организация создана');
        }catch (\Exception $e){
            return redirect()->route('cabinet.profile.organization.create',$user)
                ->with('error', 'Организация не создана');
        }
    }

    public function edit(User $user)
    {
        return view('cabinet.profile.organization.edit',[
            'user'=>$user,
            'organization'=>$user->organization,
            'regions'=>$this->regionService->dropDownRegion()
        ]);
    }

    public function update(CabinetEditRequest $request,User $user){

            $this->service->editProfile($request,$user->organization);
            return redirect()->route('cabinet.profile.organization.edit',$user)
                ->with('success', 'Организация отредактирована');

    }

    private function returnViewCategory($name)
    {
        return view('cabinet.profile.user._category_new',[
            'name'=>$name,
            'parents'=>$this->categoryService->dropDownParent(),
        ]);
    }
}

app/Http/Controllers/Cabinet/ResumeController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Entities\User\User;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ResumeController extends Controller
{
    public function index(User $user)
    {
        $resumes=$user->resumes;
        return view('cabinet.resumes',compact('resumes','user'));
    }
}

app/Http/Controllers/Cabinet/VacanciesController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Entities\User\User;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class VacanciesController extends Controller
{
    public function index(User $user)
    {
        $vacancies=$user->vacancies;
        return view('cabinet.vacancy',compact('vacancies','user'));
    }
}

resources/views/cabinet/reviews/customer.blade.php
@extends('layouts.app')
@section('meta')
    <title>Отзывы</title>
@endsection
@section('content')
    <section class="content">
        <div class="container">
            <div class="w-back lk">
                <h1>Мои отзывы</h1>
                <div class="row">
                    <div class="col-xs-12 col-md-3">
                        @include('cabinet.includes.menu',['view'=>'reviews','user'=>$user])
                    </div>
                    <div class="col-xs-12 col-md-9">
                        <p class="lead">Всего отзывов: {{$reviews->count()}}</p>
                        <div class="row">
                            <div class="col-xs-12 col-sm-6 col-lg-7">
                                <div class="radio-group inline">
                                    <label class="btn btn-lg active">
                                        <a href="{{route('cabinet.task.reviews.customer',$user)}}" > Мои отзывы </a>
                                    </label>
                                    <label class="btn btn-lg">
                                        <a href="{{route('cabinet.task.reviews.executor',$user)}}" > Обо мне </a>
                                    </label>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-6 col-lg-5">
                                <div class="mid-mark">
                                    <span class="h5">Средняя оценка: {{$user->score}}</span>
                                    <div class="rateit svg" data-rateit-value="{{$user->score}}" data-rateit-ispreset="true" data-rateit-starwidth="14" data-rateit-starheight="13" data-rateit-readonly="true"></div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane fade in active" id="my-views">
                                <div class="row">
                                    @foreach($reviews as $review)
                                        @include('cabinet.reviews.includes.customer_review',['review'=>$review])
                                    @endforeach
                                </div>
                            </div>
                        </div>
                        {{$reviews->render('layouts.includes.paginate')}}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('scripts')
    <script type="text/javascript">

        $(document).ready(function(){
            $('.phone-button').click(function(){
                let opp = $(this).attr('data-phone'),
                    gopp = $(this).text();
                $(this).html('<svg width="14" height="16"><use xlink:href="#icon-phone"></use></svg>'+opp).attr('data-phone', gopp);
            });
            $('.ui.dropdown').dropdown();
        });
    </script>
@endsection

resources/views/cabinet/reviews/executor.blade.php
@extends('layouts.app')
@section('meta')
    <title>Отзывы</title>
@endsection
@section('content')
    <section class="content">
    <div class="container">
        <div class="w-back lk">
            <h1>Мои отзывы</h1>
            <div class="row">
                <div class="col-xs-12 col-md-3">
                    @include('cabinet.includes.menu',['view'=>'reviews','user'=>$user])
                </div>
                <div class="col-xs-12 col-md-9">
                    <p class="lead">Всего отзывов: 1</p>
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-lg-7">
                            <div class="radio-group inline">
                                <label class="btn btn-lg">
                                    <a href="{{route('cabinet.task.reviews.customer',$user)}}" > Мои отзывы </a>
                                </label>
                                <label class="btn btn-lg active">
                                    <a href="{{route('cabinet.task.reviews.executor',$user)}}}" > Обо мне </a>
                                </label>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-lg-5">
                            <div class="mid-mark">
                                <span class="h5">Средняя оценка: {{$user->score}}</span>
                                <div class="rateit svg" data-rateit-value="{{$user->score}}" data-rateit-ispreset="true" data-rateit-starwidth="14" data-rateit-starheight="13" data-rateit-readonly="true"></div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade in active" id="my-views">
                            <div class="row">
                                @foreach($reviews as $review)
                                    @include('cabinet.reviews.includes.executor_review',['review'=>$review])
                                @endforeach
                            </div>
                        </div>
                    </div>
                    {{$reviews->render('layouts.includes.paginate')}}
                </div>
            </div>
        </div>
    </div>
</section>
@endsection
@section('scripts')
    <script type="text/javascript">

        $(document).ready(function(){
            $('.phone-button').click(function(){
                let opp = $(this).attr('data-phone'),
                    gopp = $(this).text();
                $(this).html('<svg width="14" height="16"><use xlink:href="#icon-phone"></use></svg>'+opp).attr('data-phone', gopp);
            });
            $('.ui.dropdown').dropdown();
        });
    </script>
@endsection