routes/web.php
<?php

use App\Http\Controllers\Cabinet\SettingController;
use App\Http\Controllers\ExecutorsController;
use App\Http\Controllers\Task\ApplicationController;
use App\Http\Controllers\Task\ResourceController;
use App\Http\Controllers\Task\ReviewController;
use App\Http\Controllers\Task\UserTaskController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\RegistrationController;
use App\Http\Controllers\Admin\User\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\RegionController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\Organization\OrganizationController;
use App\Http\Controllers\Cabinet\Profile\UserProfileController;
use App\Http\Controllers\Cabinet\Profile\OrganizationProfileController;
use App\Http\Controllers\Admin\Handbook\HandbookTitleController;
use App\Http\Controllers\Admin\Handbook\HandbookController;
use App\Http\Controllers\Cabinet\Task\TaskController;
use \App\Http\Controllers\Admin\Task\TaskController as AdminTaskController;
use App\Http\Controllers\Cabinet\Message\ChatController;


Route::get('/', [HomeController::class, 'index'])->name('home');

Route::post('/message/{user}',[\App\Http\Controllers\MessageController::class,'message']);

Route::group(
    [
    'prefix' => 'registration',
    'as' => 'registration.'
    ],
    function (){
        Route::get('/',[RegistrationController::class,'registerTab'])->name('tab');
        Route::get('individual',[RegistrationController::class,'individual'])->name('individual');
        Route::get('entity',[RegistrationController::class,'entity'])->name('entity');
        Route::post('user',[RegistrationController::class,'user'])->name('user');
        Route::post('organization',[RegistrationController::class,'organization'])->name('organisation');
    }
);

Auth::routes();

Route::group(
    [
        'prefix' => 'cabinet',
        'as' => 'cabinet.',
        'namespace' => 'Cabinet',
        'middleware' => ['auth'],
    ],
    function () {
        Route::group([
            'prefix' => 'profile',
            'as' => 'profile.',
            'namespace' => 'Profile',
        ],function (){
            Route::group([
                'prefix'=>'user', 'as'=> 'user.', 'namespace'=>'User'],function (){
                Route::get('/{user}',[UserProfileController::class,'form'])->name('form');
                Route::post('/add_avatar',[UserProfileController::class,'addAvatar'])->name('avatar.create');
                Route::delete('/delete_avatar/{user}',[UserProfileController::class,'deleteAvatar'])->name('avatar.delete');
                Route::post('/add_file',[UserProfileController::class,'addFile'])->name('file.create');
                Route::post('/car',[UserProfileController::class,'addCarForm'])->name('car');
                Route::post('/category',[UserProfileController::class,'addCategoryForm'])->name('category');
                Route::post('/sub_category',[UserProfileController::class,'addSubCategory'])->name('sub.category');
                Route::put('/store/{user}',[UserProfileController::class,'store'])->name('store');
                Route::delete('/delete_car',[UserProfileController::class,'deleteCar'])->name('car.delete');
            });

            Route::group(['prefix'=>'organization','as'=>'organization.','namespace'=>'Organization'],function (){
                Route::get('/create/{user}',[OrganizationProfileController::class,'create'])->name('create');
                Route::post('/create/{user}',[OrganizationProfileController::class,'store'])->name('store');
                Route::get('/edit/{user}',[OrganizationProfileController::class,'edit'])->name('edit');
                Route::put('/edit/{user}',[OrganizationProfileController::class,'update'])->name('update');
                Route::post('/category',[OrganizationProfileController::class,'addCategoryForm'])->name('category');
                Route::post('/sub_category',[OrganizationProfileController::class,'addSubCategory'])->name('sub.category');
                Route::post('/add_logo',[OrganizationProfileController::class,'addLogo'])->name('logo.create');
                Route::delete('/delete_logo/{user}',[OrganizationProfileController::class,'deleteLogo'])->name('logo.delete');
            });
        });
        Route::group(['prefix'=>'setting','as'=>'setting.','namespace'=>'Setting'],function(){
            Route::get('/{user}',[SettingController::class,'form'])->name('form');
            Route::put('/edit/{user}',[SettingController::class,'store'])->name('edit');
        });
        Route::group(['prefix'=>'task','as'=>'task.','namespace'=>'Task'],function(){
            Route::get('/{user}/customer/{status?}',[TaskController::class,'customer'])->name('customer');
            Route::get('/{user}/executor/{status?}',[TaskController::class,'executor'])->name('executor');
            Route::get('/{user}/reviews/customer',[\App\Http\Controllers\Cabinet\Task\ReviewController::class,'customer'])->name('reviews.customer');
            Route::get('/{user}/reviews/executor',[\App\Http\Controllers\Cabinet\Task\ReviewController::class,'executor'])->name('reviews.executor');
        });
        Route::group(['prefix'=>'message','as'=>'message.','namespace'=>'Message'],function(){
            Route::get('/{user}/chats/{opponents?}',[ChatController::class,'index'])->name('chats');
            Route::post('/{user}/chatroom',[ChatController::class,'chatroom'])->name('chatroom');
        });
        Route::get('/{user}/resumes/',[\App\Http\Controllers\Cabinet\ResumeController::class,'index'])->name('resume');
        Route::get('/{user}/vacancies/',[\App\Http\Controllers\Cabinet\VacanciesController::class,'index'])->name('vacancy');
        Route::get('/{user}/notification',[\App\Http\Controllers\Cabinet\Message\NotificationController::class,'index'])->name('notification');
        Route::get('/notification/view/{notification}',[\App\Http\Controllers\Cabinet\Message\NotificationController::class,'view'])->name('notification.view');
    });



Route::namespace('Executors')->prefix('executors')->as('executors.')->group(function(){
    Route::get('/',[ExecutorsController::class,'index'])->name('executors');
    Route::get('/category/{slug}',[ExecutorsController::class,'getBySlug'])->name('category');
});

Route::get('/user/{user}',[App\Http\Controllers\UserController::class,'show'])->name('user');

Route::namespace('Task')->prefix('task')->as('task.')->group(function (){
    Route::get('/',[ResourceController::class,'index'])->name('index');
    Route::get('/category/{slug}',[ResourceController::class,'getBySlug'])->name('category');
    Route::get('/show/{slug}',[ResourceController::class,'show'])->name('show');
    Route::namespace('Resource')->prefix('resource')->as('resource.')->middleware(['auth'])->group(function(){
        Route::get('/create',[ResourceController::class,'form'])->name('form');
        Route::post('/start/{task?}',[ResourceController::class,'start'])->name('start');
        Route::post('/finish/{task?}',[ResourceController::class,'finish'])->name('finish');
        Route::post('/full/{task?}',[ResourceController::class,'full'])->name('full');
        Route::post('/date/{task}',[ResourceController::class,'date'])->name('date');
        Route::post('/create',[ResourceController::class,'store'])->name('store');
        Route::post('/sub_category',[ResourceController::class,'addSubCategory'])->name('sub.category');
        Route::get('/update/{task}',[ResourceController::class,'update'])->name('update');
        Route::put('/edit/{task}',[ResourceController::class,'edit'])->name('edit');
        Route::delete('delete/{task}',[ResourceController::class,'delete'])->name('delete');
    });
    Route::namespace('User')->prefix('user')->as('user.')->group(function (){
        Route::get('/create/{user}',[UserTaskController::class,'create'])->name('create');
        Route::post('/create/{user}',[UserTaskController::class,'store'])->name('store');
        Route::post('/start',[UserTaskController::class,'start'])->name('start');
    });
    Route::namespace('Application')->prefix('application')->as('application.')->middleware(['auth'])->group(function(){
        Route::post('/create/{task}',[ApplicationController::class,'create'])->name('create');
        Route::post('/add-general/{task}',[ApplicationController::class,'addGeneralApplication'])->name('add.general');
        Route::get('/refused/{application}',[ApplicationController::class,'refused'])->name('refused');
        Route::get('/closed/{application}',[ApplicationController::class,'closed'])->name('closed');
    });
    Route::post('/add_reviews/{application}',[ReviewController::class,'addReviews'])->name('add.reviews');
});

Route::group(
    [
        'prefix' => 'vacancy',
        'as' => 'vacancy.',
        'namespace' => 'Vacancy',
    ],
    function(){
        Route::get('/',[\App\Http\Controllers\Vacancy\VacancyController::class,'index'])->name('index');
        Route::get('/create',[\App\Http\Controllers\Vacancy\VacancyController::class,'create'])->middleware('auth')->name('create');
        Route::post('/create',[\App\Http\Controllers\Vacancy\VacancyController::class,'store'])->middleware('auth')->name('store');
        Route::get('/edit/{vacancy}',[\App\Http\Controllers\Vacancy\VacancyController::class,'edit'])->middleware('auth')->name('edit');
        Route::put('/edit/{vacancy}',[\App\Http\Controllers\Vacancy\VacancyController::class,'update'])->middleware('auth')->name('update');
        Route::get('/show/{vacancy}',[\App\Http\Controllers\Vacancy\VacancyController::class,'show'])->name('show');
        Route::get('/{category}',[\App\Http\Controllers\Vacancy\VacancyController::class,'getByCategoryId'])->name('category');
        Route::delete('/{vacancy}',[\App\Http\Controllers\Vacancy\VacancyController::class,'remove'])->name('remove');

app/Http/Controllers/Admin/Task/TaskController.php
<?php

namespace App\Http\Controllers\Admin\Task;

use App\Entities\Task\Task;
use App\Helpers\ArrayHelpers;
use App\Http\Controllers\Controller;
use App\Services\CategoryService;
use App\Services\Task\TaskService;
use Illuminate\Http\Request;

class TaskController extends Controller
{

    public $service;
    public $categoryService;

    public function __construct(TaskService $service,CategoryService $categoryService)
    {
        $this->service=$service;
        $this->categoryService=$categoryService;
    }

    public function index()
    {
        return view('admin.task.index',
            [
                'tasks'=>$this->service->repository->all(),
                'categoryParent'=>array_merge([''=>''],ArrayHelpers::map($this->categoryService->repository->allParent(),'name','name'))
            ]
        );
    }

    public function show(Task $task)
    {
        return view('admin.task.show',compact('task'));
    }


    public function destroy(Task $task)
    {
        $this->service->delete($task);
        return redirect()->route('admin.task.show',$task)
            ->with('success', 'Вакансия удалена');
    }

    public function subCategory(Request $request)
    {
        $request->validate([
            'name'=>'required|string|exists:categories,name'
        ]);
        $category=$this->categoryService->repository->oneByName($request->name);
        return $category->subCategoryArray($category);
    }
}

app/Http/Controllers/Cabinet/Task/ReviewController.php
<?php

namespace App\Http\Controllers\Cabinet\Task;

use App\Entities\User\User;
use App\Http\Controllers\Controller;
use App\Services\Task\ReviewsService;
use Illuminate\Http\Request;

class ReviewController extends Controller
{
    public $service;

    public function __construct(ReviewsService $service)
    {
        $this->service=$service;
    }

    public function customer(User $user){
        $reviews=$this->service->repository->getReviewsByCustomer($user->id)->paginate(12);
        return view('cabinet.reviews.customer',compact('user','reviews'));
    }

    public function executor(User $user){
        $reviews=$user->reviews()->paginate(12);
        return view('cabinet.reviews.executor',compact('user','reviews'));
    }

}

app/Http/Controllers/Cabinet/Task/TaskController.php
<?php

namespace App\Http\Controllers\Cabinet\Task;

use App\Entities\User\User;
use App\Http\Controllers\Controller;
use App\Http\Requests\Task\CabinetSearchRequest;
use App\Http\Search\TaskCabinetSearch;
use Illuminate\Http\Request;

class TaskController extends Controller
{
    public function customer(CabinetSearchRequest $request, User $user)
    {
        return view('cabinet.task.customer',[
            'tasks'=>(new TaskCabinetSearch())->search($request,$user),
            'user'=>$user,
            'taskCount'=>$user->tasksCreator()->count(),
            'status'=>$request->status
        ]);
    }

    public function executor(CabinetSearchRequest $request,User $user)
    {
        return view('cabinet.task.executor',[
            'tasks'=>(new TaskCabinetSearch())->search($request,$user,'executor'),
            'user'=>$user,
            'taskCount'=>$user->tasksExecutor()->count(),
            'status'=>$request->status
        ]);
    }
}

app/Http/Controllers/Task/ApplicationController.php
<?php

namespace App\Http\Controllers\Task;

use App\Entities\Notification;
use App\Entities\Task\Application;
use App\Entities\Task\Task;
use App\Events\NotificationEvent;
use App\Http\Controllers\Controller;
use App\Http\Requests\Application\CreateRequest;
use App\Services\Task\ApplicationService;
use App\Services\Task\TaskService;
use Illuminate\Http\Request;

class ApplicationController extends Controller
{
    public $service;
    public $taskService;

    public function __construct(ApplicationService $service, TaskService $taskService)
    {
        $this->service=$service;
        $this->taskService=$taskService;
    }

    public function create(CreateRequest $request,Task $task)
    {
        try{
            $this->service->create($request,$task);
            event(new NotificationEvent(Task::class,$task->id,$task->user));
            return redirect()->route('task.show',$task->slug)
                ->with('success', 'Заявка подана');
        }catch (\Exception $e){
            return redirect()->route('task.show',$task->slug)
                ->with('error', 'Заявка не подана');
        }
    }

    public function addGeneralApplication(Request $request,Task $task)
    {
        try {
            $request->validate([
                'application' => "required|int|exists:applications,id"
            ]);
            $this->taskService->addGeneral($this->service->repository->one($request->application), $task);
            event(new NotificationEvent(Application::class,$task->id,$task->application->user,Application::TYPE_OPEN));
            return redirect()->route('task.show', $task->slug)
                ->with('success', 'Заявка подтверждена на исполнение');
        } catch (\Exception $e){
            return redirect()->route('task.show',$task->slug)
                ->with('error', 'Заявка не подтверждена на исполнение');
        }
    }

    public function refused(Application $application)
    {
        try {
            $this->service->refused($application,$application->task);
            return back()->with('success','Вы отказались от заявки');
        }catch (\DomainException $e){
            return back()->with('error',$e->getMessage());
        }catch (\Exception $e){
            return back()->with('error','Ой что-то пошло не так');
        }
    }

    public function closed(Application $application)
    {
        try {
            $this->service->closed($application,$application->task);
            return back()->with('success','Вы закрыли заявку');
        }catch (\DomainException $e){
            return back()->with('error',$e->getMessage());
        }catch (\Exception $e){
            return back()->with('error','Ой что-то пошло не так');
        }
    }
}

app/Http/Controllers/Task/ReviewController.php
<?php

namespace App\Http\Controllers\Task;

use App\Entities\Task\Application;
use App\Http\Controllers\Controller;
use App\Http\Requests\Reviews\AddRequest;
use App\Services\Task\ReviewsService;
use Illuminate\Http\Request;

class ReviewController extends Controller
{
    public $service;

    public function __construct(ReviewsService $service)
    {
        $this->service=$service;
    }

    public function addReviews(AddRequest $request, Application $application)
    {
        try{
            $this->service->create($request,$application);
            return redirect()->route('task.show',$application->task->slug)
                ->with('success', 'Отзыв оставлен');
        }catch (\Exception $e){
            return redirect()->route('task.show',$application->task->slug)
                ->with('error', 'Отзыв не оставлен');
        }
    }
}

resources/views/task/includes/_application.blade.php
<div class="proposes closed">
    <p class="h3">Исполнитель задания</p>
    <div class="propose">
        <div class="row">
            <div class="col-xs-12 col-sm-5 col-md-3">
                <div class="man-block inline size-xxs text-left">
                    <div class="left">
                        @include('layouts.includes.avatar',['user'=>$application->user])
                        <div class="about">
                            <a href="{{'user',$application->user->id}}">{{$application->user->name}}
                                @include('layouts.includes.user_moderate',['user'=>$application->user])
                            </a>
                            @include('layouts.includes.user_score',['user'=>$application->user])
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-7 col-md-9">
                <div class="quest">
                    <div class="price"><b>Исполнитель предложил <span>{{$application->price}} ₽</span></b></div>
                    <p>{{$application->comment}}</p>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/task/includes/_applications.blade.php
<div class="proposes">
    <p class="h3">У задания {{$task->applications->count()}} предложение</p>
    <div class="divider horizontal left">Новые предложения</div>
    @foreach($task->new_applications as $application)
        <div class="propose">
            <div class="row">
                <div class="col-xs-12 col-sm-5 col-md-3">
                    <div class="man-block inline size-xxs text-left">
                        <div class="left">
                            @include('layouts.includes.avatar',['user'=>$application->user])
                            <div class="about">
                                <a href="{{route('user',$application->user)}}">{{$application->user->name}}
                                    @include('layouts.includes.user_moderate',['user'=>$application->user])
                                </a>
                                @include('layouts.includes.user_score',['user'=>$application->user])
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-7 col-md-6">
                    <div class="quest">
                        <div class="price"><b>Исполнитель предложил <span>{{$application->price}} ₽</span></b></div>
                        <p>{{$application->comment}}</p>
                    </div>
                </div>
                <div class="col-xs-12 col-md-3">
                    {{Form::open(['route'=>(['task.application.add.general',$task->id])])}}
                        @method('POST')
                        {{Form::hidden('application',$application->id)}}
                        {{Form::submit('Выбрать исполнителя',['class'=>"btn btn-lg btn-gradient"])}}
                    {{Form::close()}}
                    <div class="btn btn-svg phone-button" data-phone="{{$application->user->phone}}"><svg width="14" height="16"><use xlink:href="#icon-phone"></use></svg>Показать телефон</div>
                    <a href="#" class="btn btn-svg chat-button">
                        <svg width="18" height="16">
                            <use xlink:href="#icon-message"></use>
                        </svg>Написать
                    </a>
                </div>
            </div>
        </div>
    @endforeach
    <div class="divider horizontal left">Просмотренные предложения</div>
    @foreach($task->view_applications as $application)
    <div class="propose">
        <div class="row">
            <div class="col-xs-12 col-sm-5 col-md-3">
                <div class="man-block inline size-xxs text-left">
                    <div class="left">
                        @include('layouts.includes.avatar',['user'=>$application->user])
                        <div class="about">
                            <a href="{{route('user',$application->user)}}">{{$application->user->name}}
                                @include('layouts.includes.user_moderate',['user'=>$application->user])
                            </a>
                            @include('layouts.includes.user_score',['user'=>$application->user])
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-7 col-md-6">
                <div class="quest">
                    <div class="price"><b>Исполнитель предложил <span>{{$application->price}} ₽</span></b></div>
                    <p>{{$application->comment}}!</p>
                </div>
            </div>
            <div class="col-xs-12 col-md-3">
                {{Form::open(['route'=>(['task.application.add.general',$task->id])])}}
                    @method('POST')
                    {{Form::hidden('application',$application->id)}}
                    {{Form::submit('Выбрать исполнителя',['class'=>"btn btn-lg btn-gradient"])}}
                {{Form::close()}}
                <div class="btn btn-svg phone-button" data-phone="{{$application->user->phone}}"><svg width="14" height="16"><use xlink:href="#icon-phone"></use></svg>Показать телефон</div>
                <a href="{{route('cabinet.message.chats',['user'=>Auth::user(),'opponents'=>$application->user])}}" class="btn btn-svg chat-button"><svg width="18" height="16"><use xlink:href="#icon-message"></use></svg>Написать</a>
            </div>
        </div>
    </div>
    @endforeach
</div>

resources/views/task/includes/_buttons.blade.php
@if($task->isCustomer()&&!$task->is_finished)
    @if(!is_object($task->application))
        <a href="{{route('task.resource.update',$task)}}" class="btn btn-default btn-lg">Редактировать</a>
        {{Form::open(['route'=>(['task.resource.delete',$task])])}}
        @method('DELETE')
            {{Form::submit('Удалить',['class'=>"btn btn-lg delete"])}}
        {{Form::close()}}
    @else
        <a id="ended" href="{{route('task.resource.delete',$task)}}" class="btn btn-default btn-lg">Завершить задание</a>
    @endif
@else
    <a href="{{route('task.resource.form')}}" class="btn btn-default btn-lg">Создать новое задание</a>
@endif
@if($task->isPermissionApplication())
    <a data-toggle="modal" data-target="#otclick" href="#" class="btn btn-gradient btn-lg">Предложить свою услугу</a>
@endif
@if($task->isExecutor()&&!$task->application->is_close)
    <a href="{{route('task.application.refused',$task->application)}}" class="btn btn-gradient btn-lg">Отказаться от исполнеия услуги</a>
    <a href="{{route('task.application.closed',$task->application)}}" class="btn btn-gradient btn-lg">Закрыть задачу</a>
@endif

resources/views/task/includes/_modal_application.blade.php
<div class="modal fade" id="otclick" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <p class="modal-title">Откликнуться на задание</p>
            </div>
            <div class="modal-body">
                {{Form::open(['route'=>(['task.application.create',$task])])}}
                <div class="form-group">
                    <label for="money-how">Стоимость выполнения</label>
                    <div class="input-group">
                        <div class="input-group-addon"><i class="rub icon"></i></div>
                        {{Form::text('price_app',old('price_app'),['class'=>"input", 'id'=>"money-how"])}}
                        @if ($errors->has('price_app'))
                            <span class="invalid-feedback"><strong>{{ $errors->first('price_app') }}</strong></span>
                        @endif
                    </div>
                </div>
                <div class="form-group">
                    <label for="comment-from-me">Комментарий</label>
                    <div class="input-group">
                        {{Form::textarea('comment',old('comment'),["class"=>"input", 'rows'=>"6", 'placeholder'=>"укажите дополнительную информацию", 'id'=>"comment-from-me"])}}
                        @if ($errors->has('comment'))
                            <span class="invalid-feedback"><strong>{{ $errors->first('comment') }}</strong></span>
                        @endif
                    </div>
                </div>
                {{Form::button('Предложить свою услугу',['type'=>"submit", 'class'=>"btn btn-gradient btn-lg"])}}
                {{Form::close()}}
            </div>
        </div>
    </div>
</div>

resources/views/task/includes/_modal_reviews.blade.php
<div id="reviev-user" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span></button>
                <p class="modal-title">Оставить отзыв</p>
            </div>
            <div class="modal-body">
                <div class="rev-block">
                    <div class="row">
                        <div class="col-xs-12 col-md-6">
                            <div class="ans">
                                <small>Кого оцениваете</small>
                                <div class="man-block inline size-xxs text-left">
                                    <div class="left">
                                        @include('layouts.includes.avatar',['user'=>$task->application])
                                        <div class="about">
                                            <a href="{{route('user',$task->application->user->id)}}">{{$task->application->user->name}} </a>
                                            <small>Когда: {{$task->application->getDateCreate()}}</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xs-12 col-md-6">
                            <div class="ans">
                                <small>Задание</small>
                                <p class="txt"><a href="{{route('task.show',$task->slug)}}">{{$task->title}}</a></p>
                            </div>
                        </div>
                    </div>
                </div>
                {{Form::open(['route'=>(['task.add.reviews',$task->application]),'class'=>'review-form'])}}
                @method('POST')
                <div class="form-group">
                    <label>Ваша оценка</label>
                    <div class="input-group">
                        {{Form::hidden('score',old('score'),['id'=>"backing-mark"])}}
                        <div id="rateit-mark" class="rateit svg" data-rateit-resetable="false" data-rateit-backingfld="#backing-mark" data-rateit-starwidth="17" data-rateit-starheight="16"></div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="review-from-me">Текст отзыва</label>
                    <div class="input-group">
                        {{Form::textarea('comment',old('comment'),
                            [
                                'class'=>"input",
                                'rows'=>"6",
                                'placeholder'=>"Ваш отзыв",
                                "id"=>"review-from-me"
                            ]
                        )}}
                    </div>
                </div>
                {{Form::submit('Оставить отзыв',["class"=>"btn btn-gradient btn-lg"])}}
                {{Form::close()}}
            </div>
        </div>
    </div>
</div>